package main

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
)

const releaseAssetBaseURL = "https://github.com/conn-castle/agent-outbox/releases/download"

var (
	stableTagPattern = regexp.MustCompile(`^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$`)
	sha256Pattern    = regexp.MustCompile(`^[0-9a-f]{64}$`)
	caskTemplate     = template.Must(template.New("cask").Parse(`# This file was generated by Agent Outbox. DO NOT EDIT.
cask "agent-outbox" do
  version "{{ .Version }}"

  on_macos do
    on_arm do
      sha256 "{{ .DarwinARM64SHA }}"
      url "{{ .ReleaseBaseURL }}/agent-outbox_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "{{ .DarwinAMD64SHA }}"
      url "{{ .ReleaseBaseURL }}/agent-outbox_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "{{ .LinuxARM64SHA }}"
      url "{{ .ReleaseBaseURL }}/agent-outbox_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "{{ .LinuxAMD64SHA }}"
      url "{{ .ReleaseBaseURL }}/agent-outbox_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agent-outbox"
  desc "Command-line client for agent-prepared work"
  homepage "https://agent-outbox.dev/"

  livecheck do
    skip "Generated for a numbered release."
  end

  binary "agent-outbox"
end
`))
)

type caskData struct {
	Version        string
	ReleaseBaseURL string
	DarwinARM64SHA string
	DarwinAMD64SHA string
	LinuxARM64SHA  string
	LinuxAMD64SHA  string
}

func main() {
	os.Exit(run(os.Args, os.Stderr))
}

func run(args []string, errOut io.Writer) int {
	if len(args) != 4 {
		fmt.Fprintf(errOut, "Usage: %s <output-cask> <release-tag> <checksums-file>\n", args[0])
		return 64
	}

	outputPath := args[1]
	tag := args[2]
	checksumsPath := args[3]
	if !stableTagPattern.MatchString(tag) {
		fmt.Fprintf(errOut, "release tag must be a stable vX.Y.Z tag: %s\n", tag)
		return 64
	}

	checksums, err := readChecksums(checksumsPath)
	if err != nil {
		fmt.Fprintf(errOut, "read checksums %s: %v\n", checksumsPath, err)
		return 1
	}

	version := strings.TrimPrefix(tag, "v")
	assetNames := []string{
		"agent-outbox_" + version + "_darwin_arm64.tar.gz",
		"agent-outbox_" + version + "_darwin_amd64.tar.gz",
		"agent-outbox_" + version + "_linux_arm64.tar.gz",
		"agent-outbox_" + version + "_linux_amd64.tar.gz",
	}
	for _, name := range assetNames {
		checksum, ok := checksums[name]
		if !ok {
			fmt.Fprintf(errOut, "required checksum is missing from %s: %s\n", checksumsPath, name)
			return 1
		}
		if !sha256Pattern.MatchString(checksum) {
			fmt.Fprintf(errOut, "checksum for %s is not a lowercase SHA-256: %s\n", name, checksum)
			return 1
		}
	}

	data := caskData{
		Version:        version,
		ReleaseBaseURL: releaseAssetBaseURL + "/" + tag,
		DarwinARM64SHA: checksums[assetNames[0]],
		DarwinAMD64SHA: checksums[assetNames[1]],
		LinuxARM64SHA:  checksums[assetNames[2]],
		LinuxAMD64SHA:  checksums[assetNames[3]],
	}

	var rendered bytes.Buffer
	if err := caskTemplate.Execute(&rendered, data); err != nil {
		fmt.Fprintf(errOut, "render cask: %v\n", err)
		return 1
	}
	if err := writeFileAtomic(outputPath, rendered.Bytes(), 0o644); err != nil {
		fmt.Fprintf(errOut, "write cask %s: %v\n", outputPath, err)
		return 1
	}
	return 0
}

func readChecksums(path string) (map[string]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	checksums := map[string]string{}
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) < 2 {
			continue
		}
		name := strings.TrimPrefix(strings.TrimPrefix(fields[1], "*"), "./")
		if _, exists := checksums[name]; exists {
			return nil, fmt.Errorf("duplicate checksum entry for %s", name)
		}
		checksums[name] = fields[0]
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return checksums, nil
}

func writeFileAtomic(path string, data []byte, mode os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	tmp, err := os.CreateTemp(dir, "."+filepath.Base(path)+".tmp-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	cleanup := true
	defer func() {
		if cleanup {
			_ = os.Remove(tmpPath)
		}
	}()

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(mode); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return err
	}
	cleanup = false
	return nil
}
