package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const (
	darwinARM64SHA = "1111111111111111111111111111111111111111111111111111111111111111"
	darwinAMD64SHA = "2222222222222222222222222222222222222222222222222222222222222222"
	linuxARM64SHA  = "3333333333333333333333333333333333333333333333333333333333333333"
	linuxAMD64SHA  = "4444444444444444444444444444444444444444444444444444444444444444"
)

func TestRunRendersStableCaskFromReleaseChecksums(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	checksumsPath := filepath.Join(dir, "checksums.txt")
	outputPath := filepath.Join(dir, "homebrew", "Casks", "agent-outbox.rb")
	checksums := strings.Join([]string{
		linuxAMD64SHA + "  agent-outbox_1.2.3_linux_amd64.tar.gz",
		darwinARM64SHA + " *./agent-outbox_1.2.3_darwin_arm64.tar.gz",
		linuxARM64SHA + "  agent-outbox_1.2.3_linux_arm64.tar.gz",
		darwinAMD64SHA + "  agent-outbox_1.2.3_darwin_amd64.tar.gz",
	}, "\n") + "\n"
	if err := os.WriteFile(checksumsPath, []byte(checksums), 0o600); err != nil {
		t.Fatal(err)
	}

	var errOut bytes.Buffer
	if code := run([]string{"rendercask", outputPath, "v1.2.3", checksumsPath}, &errOut); code != 0 {
		t.Fatalf("run returned %d: %s", code, errOut.String())
	}
	content, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatal(err)
	}

	want := `# This file was generated by Agent Outbox. DO NOT EDIT.
cask "agent-outbox" do
  version "1.2.3"

  on_macos do
    on_arm do
      sha256 "` + darwinARM64SHA + `"
      url "https://github.com/conn-castle/agent-outbox/releases/download/v1.2.3/agent-outbox_#{version}_darwin_arm64.tar.gz",
          verified: "github.com/conn-castle/agent-outbox/"
    end
    on_intel do
      sha256 "` + darwinAMD64SHA + `"
      url "https://github.com/conn-castle/agent-outbox/releases/download/v1.2.3/agent-outbox_#{version}_darwin_amd64.tar.gz",
          verified: "github.com/conn-castle/agent-outbox/"
    end
  end
  on_linux do
    on_arm do
      sha256 "` + linuxARM64SHA + `"
      url "https://github.com/conn-castle/agent-outbox/releases/download/v1.2.3/agent-outbox_#{version}_linux_arm64.tar.gz",
          verified: "github.com/conn-castle/agent-outbox/"
    end
    on_intel do
      sha256 "` + linuxAMD64SHA + `"
      url "https://github.com/conn-castle/agent-outbox/releases/download/v1.2.3/agent-outbox_#{version}_linux_amd64.tar.gz",
          verified: "github.com/conn-castle/agent-outbox/"
    end
  end

  name "agent-outbox"
  desc "Command-line client for agent-prepared work"
  homepage "https://agent-outbox.dev/"

  livecheck do
    skip "Generated for a numbered release."
  end

  binary "agent-outbox"
end
`
	if string(content) != want {
		t.Fatalf("rendered cask mismatch\n--- got ---\n%s\n--- want ---\n%s", content, want)
	}
}

func TestRunRejectsInvalidInputsWithoutWritingCask(t *testing.T) {
	t.Parallel()
	validChecksums := strings.Join([]string{
		darwinARM64SHA + "  agent-outbox_1.2.3_darwin_arm64.tar.gz",
		darwinAMD64SHA + "  agent-outbox_1.2.3_darwin_amd64.tar.gz",
		linuxARM64SHA + "  agent-outbox_1.2.3_linux_arm64.tar.gz",
		linuxAMD64SHA + "  agent-outbox_1.2.3_linux_amd64.tar.gz",
	}, "\n") + "\n"

	tests := []struct {
		name      string
		tag       string
		checksums string
		wantCode  int
		wantErr   string
	}{
		{name: "prerelease tag", tag: "v1.2.3-rc.1", checksums: validChecksums, wantCode: 64, wantErr: "stable vX.Y.Z"},
		{name: "missing architecture", tag: "v1.2.3", checksums: strings.ReplaceAll(validChecksums, linuxAMD64SHA+"  agent-outbox_1.2.3_linux_amd64.tar.gz\n", ""), wantCode: 1, wantErr: "required checksum is missing"},
		{name: "invalid checksum", tag: "v1.2.3", checksums: strings.Replace(validChecksums, darwinARM64SHA, "not-a-checksum", 1), wantCode: 1, wantErr: "not a lowercase SHA-256"},
		{name: "duplicate entry", tag: "v1.2.3", checksums: validChecksums + darwinARM64SHA + "  agent-outbox_1.2.3_darwin_arm64.tar.gz\n", wantCode: 1, wantErr: "duplicate checksum entry"},
	}

	for _, test := range tests {
		test := test
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			dir := t.TempDir()
			checksumsPath := filepath.Join(dir, "checksums.txt")
			outputPath := filepath.Join(dir, "Casks", "agent-outbox.rb")
			if err := os.WriteFile(checksumsPath, []byte(test.checksums), 0o600); err != nil {
				t.Fatal(err)
			}

			var errOut bytes.Buffer
			if code := run([]string{"rendercask", outputPath, test.tag, checksumsPath}, &errOut); code != test.wantCode {
				t.Fatalf("run returned %d, want %d: %s", code, test.wantCode, errOut.String())
			}
			if !strings.Contains(errOut.String(), test.wantErr) {
				t.Fatalf("stderr %q does not contain %q", errOut.String(), test.wantErr)
			}
			if _, err := os.Stat(outputPath); !os.IsNotExist(err) {
				t.Fatalf("output should not exist after failure, stat error: %v", err)
			}
		})
	}
}
