// Code generated by node scripts/system-contract.mjs generate; DO NOT EDIT.

package foundation

const (
	SystemContractHostedAppBaseURL                   = "https://app.agent-outbox.dev"
	SystemContractScheduledCleanupCron               = "17 * * * *"
	SystemContractInputSubmissionBodyBytes           = 128000
	SystemContractHumanAnswerResponseBodyBytes       = 128000
	SystemContractRawFileBytes                       = 32000000
	SystemContractOutputPageDefaultLimit             = 25
	SystemContractOutputPageMaxLimit                 = 100
	SystemContractControlPlaneSetupCodeExpirySeconds = 600
	SystemContractDefaultDevicePollIntervalSeconds   = 5
	SystemContractUnacknowledgedOutputTimeoutDays    = 14
	SystemContractBillingDowngradeGraceDays          = 7
)
